data_params:
  batch_size: 128
  fast_dataset: true
  ks:
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  l: 512
  ps:
  - 0.09622888483605832
  - 0.2442626914976671
  - 0.18806786558416266
  - 0.1538105944677268
  - 0.04008515784535251
  - 0.0400789607764453
  - 0.014923157613654134
  - 0.22254268737893326
  transition_paramss:
  - random_state: 44131
    type: dense
  - random_state: 60263
    type: dense
  - random_state: 16023
    type: dense
  - random_state: 41090
    type: dense
  - random_state: 67221
    type: dense
  - random_state: 64820
    type: dense
  - random_state: 769
    type: dense
  - random_state: 59735
    type: dense
  two_token_input: false
exp_dir: ./data/markov_mixture/final_v1/default_long_rope_only_nheads/nhead=8/n=8
mask_loss: false
memo:
  flops_per_step: 95026151424
model_params:
  gpt_config:
    in_size: 676
    n_embd: 64
    n_head: 8
    n_layer: 2
    pos_embed: false
    rope: true
    tokenized: true
  model_type: transformer
  optimizer_params:
    betas:
    - 0.9
    - 0.95
    lr: 0.0006
    weight_decay: 0.1
  optimizer_type: AdamW
seed: 0
task: markov_mixture
training_params:
  n_steps: 105234
  save_opt: false
  save_steps:
  - 29
  - 35
  - 41
  - 49
  - 58
  - 69
  - 81
  - 96
  - 113
  - 134
  - 158
  - 187
  - 221
  - 261
  - 309
  - 365
  - 431
  - 509
  - 601
  - 710
  - 839
  - 991
  - 1171
  - 1383
  - 1634
  - 1931
  - 2281
  - 2694
  - 3183
  - 3760
  - 4441
  - 5246
  - 6197
  - 7321
  - 8648
  - 10216
  - 12068
  - 14255
  - 16839
  - 19892
  - 23497
  - 27757
  - 32788
  - 38732
  - 45752
  - 54046
  - 63842
  - 75415
  - 89085
  - 105234
wandb:
  group: final_v1/default_long_rope_only_nheads
  name: nhead=8_n=8
  project: markov_mixture
