data_params:
  batch_size: 128
  fast_dataset: true
  ks:
  - 10
  - 10
  - 10
  - 10
  l: 128
  ps:
  - 0.1410215567872302
  - 0.3579622176722185
  - 0.27560979462158475
  - 0.22540643091896656
  transition_paramss:
  - random_state: 54886
    type: dense
  - random_state: 6265
    type: dense
  - random_state: 82386
    type: dense
  - random_state: 37194
    type: dense
  two_token_input: false
exp_dir: ./data/markov_mixture/final_v1/default_long_rope_only_ls/l=128/n=4
mask_loss: false
memo:
  flops_per_step: 13035896832
model_params:
  gpt_config:
    block_size: 1024
    in_size: 676
    n_embd: 64
    n_head: 4
    n_layer: 2
    pos_embed: false
    rope: true
    tokenized: true
  model_type: transformer
  optimizer_params:
    betas:
    - 0.9
    - 0.95
    lr: 0.0006
    weight_decay: 0.1
  optimizer_type: AdamW
seed: 0
task: markov_mixture
training_params:
  n_steps: 767112
  save_opt: false
  save_steps:
  - 29
  - 36
  - 45
  - 55
  - 68
  - 84
  - 103
  - 127
  - 157
  - 193
  - 238
  - 292
  - 360
  - 443
  - 545
  - 670
  - 824
  - 1014
  - 1248
  - 1535
  - 1888
  - 2323
  - 2858
  - 3516
  - 4325
  - 5320
  - 6545
  - 8051
  - 9904
  - 12183
  - 14987
  - 18436
  - 22680
  - 27899
  - 34320
  - 42218
  - 51934
  - 63887
  - 78589
  - 96676
  - 118925
  - 146294
  - 179962
  - 221378
  - 272326
  - 334998
  - 412094
  - 506933
  - 623598
  - 767112
wandb:
  group: final_v1/default_long_rope_only_ls
  name: l=128_n=4
  project: markov_mixture
