data_params:
  batch_size: 128
  fast_dataset: true
  ks:
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  l: 1024
  ps:
  - 0.09622888483605832
  - 0.2442626914976671
  - 0.18806786558416266
  - 0.1538105944677268
  - 0.04008515784535251
  - 0.0400789607764453
  - 0.014923157613654134
  - 0.22254268737893326
  transition_paramss:
  - random_state: 44131
    type: dense
  - random_state: 60263
    type: dense
  - random_state: 16023
    type: dense
  - random_state: 41090
    type: dense
  - random_state: 67221
    type: dense
  - random_state: 64820
    type: dense
  - random_state: 769
    type: dense
  - random_state: 59735
    type: dense
  two_token_input: false
exp_dir: ./data/markov_mixture/final_v1/default_long_rope_only_ls/l=1024/n=8
mask_loss: false
memo:
  flops_per_step: 293131517952
model_params:
  gpt_config:
    block_size: 1024
    in_size: 676
    n_embd: 64
    n_head: 4
    n_layer: 2
    pos_embed: false
    rope: true
    tokenized: true
  model_type: transformer
  optimizer_params:
    betas:
    - 0.9
    - 0.95
    lr: 0.0006
    weight_decay: 0.1
  optimizer_type: AdamW
seed: 0
task: markov_mixture
training_params:
  n_steps: 34114
  save_opt: false
  save_steps:
  - 29
  - 34
  - 39
  - 46
  - 53
  - 61
  - 71
  - 81
  - 94
  - 109
  - 126
  - 145
  - 168
  - 194
  - 223
  - 258
  - 298
  - 344
  - 397
  - 459
  - 530
  - 612
  - 706
  - 815
  - 941
  - 1086
  - 1254
  - 1448
  - 1672
  - 1930
  - 2228
  - 2572
  - 2969
  - 3428
  - 3958
  - 4569
  - 5274
  - 6089
  - 7029
  - 8115
  - 9368
  - 10814
  - 12484
  - 14412
  - 16638
  - 19207
  - 22173
  - 25597
  - 29550
  - 34113
wandb:
  group: final_v1/default_long_rope_only_ls
  name: l=1024_n=8
  project: markov_mixture
