data_params:
  batch_size: 128
  fast_dataset: true
  ks:
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  l: 512
  ps:
  - 0.09622888483605832
  - 0.2442626914976671
  - 0.18806786558416266
  - 0.1538105944677268
  - 0.04008515784535251
  - 0.0400789607764453
  - 0.014923157613654134
  - 0.22254268737893326
  transition_paramss:
  - random_state: 44131
    type: dense
  - random_state: 60263
    type: dense
  - random_state: 16023
    type: dense
  - random_state: 41090
    type: dense
  - random_state: 67221
    type: dense
  - random_state: 64820
    type: dense
  - random_state: 769
    type: dense
  - random_state: 59735
    type: dense
  two_token_input: false
exp_dir: ./data/markov_mixture/final_v1/default_long_rope_only_ks/k=4/n=8
mask_loss: false
memo:
  flops_per_step: 92610232320
model_params:
  gpt_config:
    in_size: 676
    n_embd: 64
    n_head: 4
    n_layer: 2
    pos_embed: false
    rope: true
    tokenized: true
  model_type: transformer
  optimizer_params:
    betas:
    - 0.9
    - 0.95
    lr: 0.0006
    weight_decay: 0.1
  optimizer_type: AdamW
seed: 0
task: markov_mixture
training_params:
  n_steps: 43191
  save_opt: false
  save_steps:
  - 29
  - 34
  - 40
  - 46
  - 54
  - 63
  - 73
  - 84
  - 98
  - 114
  - 132
  - 153
  - 178
  - 206
  - 239
  - 277
  - 322
  - 373
  - 433
  - 503
  - 583
  - 677
  - 785
  - 911
  - 1056
  - 1225
  - 1422
  - 1649
  - 1913
  - 2219
  - 2574
  - 2986
  - 3464
  - 4019
  - 4662
  - 5407
  - 6273
  - 7276
  - 8440
  - 9791
  - 11358
  - 13175
  - 15283
  - 17728
  - 20564
  - 23854
  - 27671
  - 32098
  - 37233
  - 43190
wandb:
  group: final_v1/default_long_rope_only_ks
  name: k=4_n=8
  project: markov_mixture
